### ISSUE TITLE
First-class CocoaPods support

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-cli#183]
I am opening this issue to track work required to offer first-class support for CocoaPods in `link` and `unlink` commands.

@fson is [working on improving general CocoaPods support](https://github.com/react-native-community/discussions-and-proposals/issues/96) in React Native and making it the integral part of every new app inited with `react-native init`.

We should make sure that CLI work is done and released before this PR gets merged.

**Comment by grabbou** [comment]
I am going to investigate this tomorrow and publish an action plan. 

@fson, do you have any deadlines on shipping this PR?

**Comment by fson** [comment]
@grabbou it would be great to have CocoaPods in the default template for RN 0.60.

I want to ship features that use CocoaPods in Expo CLI soon (in February). Those features will initially have to patch the template for CocoaPods support (because we support older RN versions), but I’d like to stop patching and move to just use the upstream template as soon as possible.

**Comment by grabbou** [comment]
Interesting. I didn't know you were using React Native template (and init) internally at Expo and needed the CocoaPods support there.

Either way, that sounds like a fair timeline. Apologies for not getting back to you last week as promised, but I've run into other things that got my attention.

I am going to investigate it as soon as possible.

**Comment by grabbou** [comment]
Going to close it in favour of auto linking.
