### ISSUE TITLE
Make link work for specified platform only

### ISSUE THREAD

**Issue by thymikee** [react-native-community/react-native-cli#25]
Basically
```sh
react-native link --platform=ios
```

**Comment by ferrannp** [comment]
A bit related to: https://github.com/react-native-community/react-native-cli/issues/3. Tbh I'd be nice first of all:

1. Not running the whole `link` because in most cases it causes things you do not want to happen
2. Have some config in `package.json` with list of packages to be linked and possibility to choose some only for android or ios

Anyway these are all ideas. What you propose should be much faster to implement in a short term time.
