### ISSUE TITLE
Update "react-native-cli" to use new CLI

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-cli#42]
It has hardcoded paths to "react-native" (old CLI location). 

Update: https://github.com/react-native-community/react-native-cli/blob/5d76ac9dcffa9cd5daa7e24bcd377b20e728faef/packages/global-cli/index.js#L64-L66 and https://github.com/react-native-community/react-native-cli/blob/5d76ac9dcffa9cd5daa7e24bcd377b20e728faef/packages/global-cli/index.js#L240-L249 to point to a new location.

Once this happens, we can remove "local-cli/cli.js" from React Native repository. Meanwhile, let's put a warning that developers should not call the CLI this way.

**Comment by fson** [comment]
Looks like this is already done, [`local-cli/cli.js` imports `react-native-local-cli`](https://github.com/facebook/react-native/blob/2f32fea79a50bdae303126f6d5288ea447f5331b/local-cli/cli.js#L12). I wouldn't go as far as removing that file from `react-native`, because existing projects created with `react-native init` reference it in the `start` script in `package.json` and tools like Expo CLI use it.

**Comment by grabbou** [comment]
Yeah, @fson, this is totally our idea. In this issue, we are talking about "react-native-cli" (npm package, global CLI) to call into the right file, instead of the proxy.

**Comment by thymikee** [comment]
@grabbou do you mean replace the `start` command with this instead of proxy?
```json
"start": "react-native-local-cli start" 
```

It would require users to install `react-native-local-cli` because of how package managers work (not every each of them hoists dependencies to the root node_modules – it's an implementation detail)

**Comment by grabbou** [comment]
We only need to replace it with "start": "react-native start" I guess. When CLI is present in the "node_modules", it should call the "bin". Otherwise, I imagine it will call the global "react-native" CLI which proxies all the calls to "node_modules" anyway.
